# This is a basic workflow to help you get started with Actions

name: Production Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: NPM Install
        run: npm install
      - name: Production Build
        run: npm run build
      - name: Deploy to S3
        run: AWS_ACCESS_KEY_ID=${{ secrets.access_key_id }} AWS_SECRET_ACCESS_KEY=${{ secrets.secret_access_key }} npm run deploy
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install, build
        run: |
          npm install
          npm run build
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.4.x
          lhci autorun
